---

- name: Initialize master
  hosts: tag__items___master____ping____ssh__
  remote_user: root
  become: yes
  become_user: root
  gather_facts: true

  vars:
    kube_user: kube_user
    kube_user_home: "/home/kube_user"

  tasks:

    ##################################
    # Empty file for Kubeadm configuring
    ##################################
    - name: Create an Empty file for Kubeadm configuring
      copy:
        content: ""
        dest: /etc/kubernetes/kubeadm-config.yaml
        force: no

    ##################################
    # Configure container runtime
    ##################################
    - name: Configure Kubernetes container runtime
      blockinfile:
        path: /etc/kubernetes/kubeadm-config.yaml
        block: |
          kind: ClusterConfiguration
          apiVersion: kubeadm.k8s.io/v1beta3
          networking:
            podSubnet: "10.244.0.0/16"
          ---
          kind: KubeletConfiguration
          apiVersion: kubelet.config.k8s.io/v1beta1
          runtimeRequestTimeout: "15m"
          cgroupDriver: "systemd"
          systemReserved:
            cpu: 100m
            memory: 350M
          kubeReserved:
            cpu: 100m
            memory: 50M
          enforceNodeAllocatable:
          - pods

    - name: Check if /var/lib/etcd exists
      command: test -d /var/lib/etcd
      register: etcd_dir
      ignore_errors: true

    - name: Clear the contents of /var/lib/etcd if it exists
      file:
        path: /var/lib/etcd
        state: absent
      when:
        - etcd_dir is defined
        - etcd_dir.rc == 0

    - name: Recreate /var/lib/etcd directory
      file:
        path: /var/lib/etcd
        state: directory
        mode: '0700'

    ##################################
    # Initialize the cluster
    ##################################
    - name: Initialize the cluster
      shell: kubeadm init --config /etc/kubernetes/kubeadm-config.yaml --ignore-preflight-errors=Mem >> cluster_initialized.log 2>&1
      args:
        chdir: "{{ kube_user_home }}"
        creates: cluster_initialized.log

    - name: Create .kube directory
      become_user: "{{ kube_user }}"
      file:
        path: "{{ kube_user_home }}/.kube"
        state: directory
        mode: '0755'

    - name: Copy admin.conf to User's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ kube_user_home }}/.kube/config"
        remote_src: yes
        owner: "{{ kube_user }}"
        group: "{{ kube_user }}"
        mode: '0644'

    ##################################
    # Install Pod Network - Flannel
    ##################################
    - name: Install Flannel Pod Network
      become_user: "{{ kube_user }}"
      shell: |
        export KUBECONFIG=/etc/kubernetes/admin.conf
        kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.log 2>&1
      args:
        chdir: "{{ kube_user_home }}"
        creates: pod_network_setup.log

    ##################################
    # Download and apply Calico network manifest
    ##################################
    - name: Download Calico network manifest
      get_url:
        url: https://projectcalico.docs.tigera.io/manifests/calico.yaml
        dest: "{{ kube_user_home }}/calico.yaml"

    - name: Set permissions on Calico manifest
      file:
        path: "{{ kube_user_home }}/calico.yaml"
        mode: '0644'
        owner: "{{ kube_user }}"
        group: "{{ kube_user }}"

    - name: Apply Calico network manifest
      become: yes
      become_user: "{{ kube_user }}"
      command: kubectl apply -f "{{ kube_user_home }}/calico.yaml"

    ##################################
    # Download and apply Kubernetes Dashboard manifest
    ##################################
    - name: Download Kubernetes Dashboard manifest
      get_url:
        url: https://raw.githubusercontent.com/kubernetes/dashboard/v2.5.0/aio/deploy/recommended.yaml
        dest: "{{ kube_user_home }}/dashboard.yaml"

    - name: Set permissions on Dashboard manifest
      file:
        path: "{{ kube_user_home }}/dashboard.yaml"
        mode: '0644'
        owner: "{{ kube_user }}"
        group: "{{ kube_user }}"

    - name: Apply Kubernetes Dashboard manifest
      become: yes
      become_user: "{{ kube_user }}"
      command: kubectl apply -f "{{ kube_user_home }}/dashboard.yaml"
