
---
- name: Example Playbook Using Ansible Vault
  hosts: localhost
  vars_files:
    - secrets.yml  # Include the encrypted file

  tasks:
    - name: Show the db_password
      debug:
        msg: "The database password is {{ db_password }}"

    - name: Show the api_key
      debug:
        msg: "The API key is {{ api_key }}"
