---
plugin: community.digitalocean.digitalocean
attributes:
  - id
  - name
  - tags
  - networks

compose:
  ansible_host: do_networks.v4 | selectattr('type','eq','public') | map(attribute='ip_address') | first
  ansible_user: "'kube_user'"
  ansible_ssh_common_args: "'-o StrictHostKeyChecking=no'"

api_token: "{{ lookup('env', 'DO_API_TOKEN')}}"