#!/usr/bin/env -S ansible-playbook -K
# NOTE: Don't provide the playbook filename in the shebang. It is added automatically.
---

- name: vaul playbook
  hosts: localhost
  vars_files:
    - secret.yaml


  tasks:

    ##################################
    # Get username and password
    ##################################
    - name: Retrieve Join Command
      debug:
        msg: "My username is: {{ db_username }} and Password is: {{ db_password }}"
      no_log: true

