#!/usr/bin/env -S ansible-playbook -K
# NOTE: Don't provide the playbook filename in the shebang. It is added automatically.
---

- name: Copy helm files playbook
  hosts: master
  remote_user: kube_user
  become: yes

  tasks:

    ##################################
    # Updates
    ##################################
    - name: Updates
      apt:
        update_cache: yes

    ##################################
    # Copy charts and helmfile
    ##################################
    - name: Copy all Helm charts and helmfile.yaml
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: '0755'
      loop:
        - { src: "../../Helm/dynamodbchart", dest: "/home/kube_user/Helm/dynamodbchart" }
        - { src: "../../Helm/chartpostgress", dest: "/home/kube_user/Helm/chartpostgress" }
        - { src: "../../Helm/bookchart", dest: "/home/kube_user/Helm/bookchart" }
        - { src: "../../Helm/employeechart", dest: "/home/kube_user/Helm/employeechart" }
        - { src: "../../Helm/chartnginx", dest: "/home/kube_user/Helm/chartnginx" }
        - { src: "../../Helm/helmfile.yaml", dest: "/home/kube_user/Helm/helmfile.yaml" }