#!/usr/bin/env -S ansible-playbook -K
# NOTE: Don't provide the playbook filename in the shebang. It is added automatically.
---
- name: Deploy NFS provisioner on Kubernetes
  hosts: master
  remote_user: kube_user
  become: yes
  tasks:

    ##################################
    # Update apt
    ##################################
    - name: Update apt cache
      apt:
        update_cache: yes

    ##################################
    # Create ConfigMap
    ##################################
    - name: Create ConfigMap for NGINX server block
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: nginx-config
            namespace: dev
          data:
            nginx.conf: |
              server {
                  listen 80;
                  server_name localhost;
                  root /usr/share/nginx/html;
                  index index.html;
              
                  location / {
                      try_files $uri $uri/ =404;
                  }
              }
            index.html: |
              <!DOCTYPE html>
              <html>
              <head>
                  <title>Welcome to my nginx</title>
                  <style>
                      body {
                          background-color: #ADD8E6; /* Light blue background */
                          color: #333333; /* Dark text color for contrast */
                          font-family: Arial, sans-serif;
                      }
                  </style>
              </head>
              <body>
                  <h1>This is the updated index.html </h1>
                  <p>Nginx server running in Kubernetes.</p>
              </body>
              </html>

      environment:
        KUBECONFIG: "/home/kube_user/.kube/config"

    ##################################
    # Create NGINX Deployment
    ##################################
    - name: Create NGINX Deployment in Kubernetes
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx
            namespace: dev
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                containers:
                  - name: nginx
                    image: nginx:latest
                    ports:
                      - containerPort: 80
                    volumeMounts:
                      - name: nginx-config-volume
                        mountPath: /usr/share/nginx/html/index.html
                        subPath: index.html
                      - name: nginx-config-volume
                        mountPath: /etc/nginx/conf.d/default.conf
                        subPath: nginx.conf
                      # a mount for site-data
                      - name: tmp-mount
                        mountPath: /tmp
                volumes:
                  - name: nginx-config-volume
                    configMap:
                      name: nginx-config
                  - name: tmp-mount
                    persistentVolumeClaim:
                      claimName: nfs-pvc
      environment:
        KUBECONFIG: "/home/kube_user/.kube/config"

    ##################################
    # Create NGINX Service
    ##################################
    - name: Create NGINX Service in Kubernetes
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: nginx-service
            namespace: dev
          spec:
            selector:
              app: nginx
            ports:
              - protocol: TCP
                port: 8080
                targetPort: 80
                nodePort: 30033
            type: LoadBalancer
            externalIPs:
              - 192.168.0.10
      environment:
        KUBECONFIG: "/home/kube_user/.kube/config"

    ##################################
    # Create NGINX Ingress
    ##################################
    - name: Create NGINX Ingress
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: nginx-ingress
            namespace: dev
            annotations:
              nginx.ingress.kubernetes.io/rewrite-target: /
          spec:
            rules:
              - host:  test.elvis.com # This will map to ur domain name
                http:
                  paths:
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: nginx-service
                          port:
                            number: 8080
      environment:
        KUBECONFIG: "/home/kube_user/.kube/config"


