#!/usr/bin/env -S ansible-playbook -K
# NOTE: Don't provide the playbook filename in the shebang. It is added automatically.
---

- name: Helm install playbook
  hosts: master
  remote_user: kube_user
  become: yes
  gather_facts: true

  tasks:

    ##################################
    # Ping servers to check connection
    ##################################
    - name: Ping servers
      ping:

    ##################################
    # Update packages
    ##################################
    - name: Update apt package cache (Debian/Ubuntu)
      apt:
        update_cache: yes
        cache_valid_time: 3600

    ##################################
    # Install helm
    ##################################
    - name: Download Helm installation script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0755'

    - name: Run Helm installation script
      command: /tmp/get_helm.sh
      args:
        creates: /usr/local/bin/helm  # Skip if Helm already installed

    - name: Verify Helm installation
      command: helm version
      register: helm_version
      changed_when: false
      failed_when: helm_version.rc != 0

    - name: Output Helm version
      debug:
        msg: "{{ helm_version.stdout }}"

    ##################################
    # Add helm repo
    ##################################
- name: Helm playbook
  hosts: master
  remote_user: kube_user
  gather_facts: true

  tasks:

    - name: Set permissions on Kubernetes config
      file:
        path: /home/kube_user/.kube/config
        owner: kube_user
        mode: '0600'

    - name: Add stable chart repo
      kubernetes.core.helm_repository:
        name: dopc02devops-repo
        repo_url: "https://dopc02devops.github.io/helms_artifacts"
      ignore_errors: yes

    - name: Update Helm repositories
      command: helm repo update

    - name: Install emp-book-apps chart
      kubernetes.core.helm:
        name: chartnginx
        chart_ref: dopc02devops-repo/chartnginx
        chart_version: "2.0.0"
        release_namespace: dev
        create_namespace: true
        update_repo_cache: true
      register: helm_deploy
      diff: yes  # Ensure diff is enabled
      changed_when: '"STATUS: deployed" in helm_deploy.stdout'

    - name: Show emp-book-apps installation status
      debug:
        msg:
          - "Stdout {{ helm_deploy.stdout }}"
          - "Deployment output {{ helm_deploy }}"
