#!/usr/bin/env -S ansible-playbook -K
# NOTE: Don't provide the playbook filename in the shebang. It is added automatically.
---
- name: Create PVC Kubernetes
  hosts: master
  remote_user: kube_user
  become: yes
  tasks:

    ##################################
    # Update apt
    ##################################
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install pip if not present
      apt:
        name: python3-pip
        state: present

    - name: Install kubernetes Python library
      pip:
        name: kubernetes
        state: present
        executable: pip3
        extra_args: --break-system-packages

    - name: Create a Kubernetes namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: dev
      ignore_errors: yes
      environment:
        KUBECONFIG: "/home/kube_user/.kube/config"

    ##################################
    # Create Persistent Volume Claim
    ##################################
    - name: Create PVC for NFS mount
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: nfs-pvc
            namespace: dev
          spec:
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 2Gi
            storageClassName: nfs-client
      environment:
        KUBECONFIG: "/home/kube_user/.kube/config"
