#!/usr/bin/env -S ansible-playbook -K
# NOTE: Don't provide the playbook filename in the shebang. It is added automatically.
---

- name: Uninstall apache and nginx playbook
  hosts: all
  remote_user: ansible_user
  become: yes
  become_user: root
  gather_facts: true
  vars:
    service_url_ubuntu: "http://157.245.39.68"
    service_url_centos: "http://157.245.39.68"
    expected_status_code: 200
    packages: [ 'wget', 'unzip', 'curl', 'git' ] # List
    web_server: { 'Ubuntu': 'apache2', 'CentOS': 'httpd' } # map

  tasks:

    ##################################
    # Ping servers to check connection
    ##################################
    - name: Check server connection via ping module
      ping:

    ##################################
    # Check service status
    ##################################
    - name: Check if the service is responding with the expected status
      ansible.builtin.uri:
        url: "{{ service_url_centos if ansible_distribution == 'CentOS' else service_url_ubuntu }}"
        method: GET
        status_code: "{{ expected_status_code }}"
        return_content: no
      register: service_response
      ignore_errors: yes

    ##################################
    # Display status code
    ##################################
    - name: Display the HTTP status code
      debug:
        msg: >
          {% if service_response.status == 200 %}
          HTTP Status Code: 200 | Service is up and running.
          {% else %}
          HTTP Status Code: {{ service_response.status if service_response is defined else 'No response' }} | Service might be down.
          {% endif %}

    ##################################
    # Display content
    ##################################
    - name: Display the response content
      debug:
        msg: "{{ service_response }}"

    ##################################
    # Uninstall apache and nginx
    ##################################
    - name: Uninstall Apache/Nginx
      package:
        name: "{{ 'nginx' if ansible_distribution == 'CentOS' else 'apache2' }}"
        state: absent

    ##################################
    # Verify apache/nginx uninstalled
    ##################################
    - name: Ensure apache/nginx is not running
      service:
        name: "{{ 'httpd' if ansible_distribution == 'CentOS' else 'apache2' }}"
        state: stopped
        enabled: no
      register: httpd_result
      ignore_errors: yes # Continue even if the task fails

    ##################################
    # Display Results
    ##################################
    - name: Display HTTP results
      debug:
          var: httpd_result
